version: "3"
services:
  mariadb:
    build:
      dockerfile: compose/DockerFile
    container_name: mdb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123456789
    volumes:
      - C:\Dockerfile\db-on-docker-ms:/var/lib/mariadb

  streaming_instance-1:
    container_name: streaming_instance-1
    build:
      dockerfile: compose/DockerFile_positions_streaming
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - cfdinstruments
      - accountpositions
      - balances
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - TOP_INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments/most-used
      - INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments-prices
      - POSITIONS_URL=http://accountpositions:8082/api/v1/users/
      - BALANCE_URL=http://balances:8085/api/v1/users/
      - KAFKA_URL=kafka:9092

  streaming_instance-2:
    container_name: streaming_instance-2
    build:
      dockerfile: compose/DockerFile_positions_streaming
    ports:
      - 8081:8080
    depends_on:
      - mariadb
      - cfdinstruments
      - accountpositions
      - balances
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - TOP_INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments/most-used
      - INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments-prices
      - POSITIONS_URL=http://accountpositions:8082/api/v1/users/
      - BALANCE_URL=http://balances:8085/api/v1/users/
      - KAFKA_URL=kafka:9092
    
  streaming_instance-3:
    container_name: streaming_instance-3
    build:
      dockerfile: compose/DockerFile_positions_streaming
    ports:
      - 8091:8080
    depends_on:
      - mariadb
      - cfdinstruments
      - accountpositions
      - balances
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - TOP_INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments/most-used
      - INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments-prices
      - POSITIONS_URL=http://accountpositions:8082/api/v1/users/
      - BALANCE_URL=http://balances:8085/api/v1/users/
      - KAFKA_URL=kafka:9092

  balances:
    container_name: balances
    build:
      dockerfile: compose/DockerFile_account_balance
    ports:
      - 8085:8085
    depends_on:
      - mariadb
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - KAFKA_URL=kafka:9092

  auth: 
    container_name: auth
    build:
      dockerfile: compose/DockerFile_authentication
    ports:
      - 8084:8084
    depends_on:
      - mariadb
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - KAFKA_URL=kafka:9092

  cfdinstruments: 
    container_name: cfdinstruments
    build:
      dockerfile: compose/DockerFile_instruments
    ports:
      - 8083:8083
    depends_on:
      - mariadb
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - KAFKA_URL=kafka:9092

  accountpositions: 
    container_name: accountpositions
    build:
      dockerfile: compose/DockerFile_positions
    ports:
      - 8082:8082
    depends_on:
      - mariadb
      - kafka
    environment: 
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - KAFKA_URL=kafka:9092
  
  quotescfd:
    container_name: quotescfd
    build:
      dockerfile: compose/DockerFile_quotes
    environment:
      - DB_URL=jdbc:mariadb://mdb:3306/cfd
      - KAFKA_URL=kafka:9092
      - INSTRUMENTS_URL=http://cfdinstruments:8083/api/v1/instruments-prices
    depends_on:
      - cfdinstruments
      - kafka
    ports:
      - 8090:8090

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
  
  haproxy:
    image: haproxy:alpine
    ports:
      - "8079:8079"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
