version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis

  mariadb:
    build:
      dockerfile: DockerFile
    container_name: mdb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_USERNAME: root
      MARIADB_ROOT_PASSWORD: 123456789
    volumes:
      - C:\Dockerfile\db-on-docker-ms:/var/lib/mariadb

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper